### ISSUE TITLE
Adding NMEA2000 dependency as a idf component

### ISSUE THREAD

**Issue by gpearcey** [ttlappalainen/NMEA2000_esp32#16]
Hi. Still learning cmake, and I'm having trouble adding NMEA2000 as a dependency for NMEA2000_esp32.  I've added NMEA2000_esp to the project and specified it's location with EXTRA_COMPONENT_DIRS in the project CMakeLists.txt but I have no idea how to add NMEA2000 as an idf component. I tried to import it as a third-party CMake library by following [this](https://github.com/espressif/esp-idf/tree/903af13e847cd301e476d8b16b4ee1c21b30b5c6/examples/build_system/cmake/import_lib) example but had no luck. I would appreciate any help. Thanks.

**Comment by jiauka** [comment]
Have a look at 
https://github.com/phatpaul/NMEA2000_switchbank_example_esp-idf
it works
