### ISSUE TITLE
esp32-c3

### ISSUE THREAD

**Issue by titio72** [ttlappalainen/NMEA2000_esp32#19]
Hi - I was trying to port my project to an ESP32-C3, but I get a compilation error for a missing file "soc/dport_reg.h"
Any plan to support the C3, or any indications on how to do it?

Thanks!

**Comment by ttlappalainen** [comment]
You can try with https://github.com/jiauka/NMEA2000_esp32xx/tree/main . It is not complete, but works somehow. I'll write new later.
