### ISSUE TITLE
ESP32 versions

### ISSUE THREAD

**Issue by merco** [ttlappalainen/NMEA2000_esp32#23]
HI. I'm about to buy an ESP32. Can you suggest a link to purchase an ESP32 that is 100% compatible with the library. I understand that some models are not fully supported.

Thank you.

PS: I Think ESP-32S ESP-WROOM-32 ESP32 WIFI  is not a good choice

**Comment by ttlappalainen** [comment]
Look https://www.espressif.com/en/products/modules Select board with some of the ESP32 modules e.g., ESP32-WROOM-32E or ESP32-WROOM-32UE. E.g., ESP32-DevKitC https://www.digikey.fi/fi/products/detail/espressif-systems/ESP32-DEVKITC-32UE/12091813?utm_adgroup=&utm_source=google&utm_medium=cpc&utm_campaign=PMAX%20Shopping_Product_High%20Performers&utm_term=&productid=12091813&utm_content=&utm_id=go_cmp-19551510472_adg-_ad-__dev-c_ext-_prd-12091813_sig-Cj0KCQjwiYOxBhC5ARIsAIvdH50MGnRtJ6mX5eoaCbFBpw2DPvWZaQO0Cw08-VyKxHA3WJ1HwEU68DIaAkhSEALw_wcB&gad_source=1&gclid=Cj0KCQjwiYOxBhC5ARIsAIvdH50MGnRtJ6mX5eoaCbFBpw2DPvWZaQO0Cw08-VyKxHA3WJ1HwEU68DIaAkhSEALw_wcB
